### ISSUE TITLE
Make a discord

### ISSUE THREAD

**Issue by googlescientificnameforapig** [MoreMcmeta/core#10]

**Comment by soir20** [comment]
I'm not a fan of using Discord for a project like this because the messages aren't indexed by search engines, and it requires you to log in to view conversations.  I also see bug reports get buried in general channels in the Discord servers I'm in for other projects; I can't monitor chat all day to catch these.

In the spirit of keeping Q&A and other discussions open, I've opted to try [GitHub Discussions](https://github.com/orgs/MoreMcmeta/discussions). Fabric has been using Discussions, and it seems pretty successful.
