### ISSUE TITLE
Enchantment glint please

### ISSUE THREAD

**Issue by katashisano** [MoreMcmeta/core#15]
I was making a texture pack for crystal pvp and I wanted to apply the enchantment glint effect to the totem, but there was no option to do that through .mcmeta file, so please, add it if possible.

**Comment by soir20** [comment]
I like this idea. Just as an FYI, I've paused new feature development on 3.x while I work on 4.x. 4.x is a big enough change that it isn't really efficient to develop features for 3.x and then port them over to 4.x, though I am still doing bug fixes for 3.x. You might wish to watch #7 for more current updates, which is highest priority and the main issue for 4.x-related things at the moment.

**Comment by katashisano** [comment]
Thanks, really useful.

**Comment by soir20** [comment]
I've finally had a chance to take a closer look at this. I originally wanted to implement this so that you could simply add `"enchanted": true` for a texture, but I've found that this isn't really workable for several technical reasons. The main reason is that the way Minecraft implements block textures doesn't work well with the sliding/translation and blur effects of the enchantment glint. The workaround the avoid that issue has the potential to impact game performance and be complicated to implement.

Now that the [emissive plugin](https://modrinth.com/mod/moremcmeta-emissive) has been finished, I decided to add an enchantment effect as an animated emissive overlay. Here's the resource pack I'm using and a GIF of the enchantment effect:

[MoreMcmeta Enchantment Demo.zip](https://github.com/MoreMcmeta/core/files/13453683/MoreMcmeta.Enchantment.Demo.zip)

![enchantment_glint](https://github.com/MoreMcmeta/core/assets/71418127/5cbf720c-5ebb-49f0-8fa3-4284e2d300e8)

For testing, I only applied the enchantment to the oak log. You can use this `.moremcmeta` file to apply the enchantment to other blocks and entities (`assets/minecraft/textures/block/oak_log.png.moremcmeta` in the pack):

```
{
    "overlay": {
        "texture": "minecraft:textures/enchantment_glint.png",
        "emissive": true,
        "transparency": "translucent"
    }
}
```

I created a command-line tool to help me generate this animation and made it available [here](https://github.com/MoreMcmeta/frame-translation-generator), in case someone wants to create their own version of the enchantment animation.

Note that you need MoreMcmeta and the [emissive plugin](https://modrinth.com/mod/moremcmeta-emissive) for the enchantment effect to appear.
